### ISSUE TITLE
Web feed

### ISSUE THREAD

**Issue by jtagcat** [scroll/marinpetrov.com#1]
I would appreciate, if I could follow your site using one of RSS/Atom/JSON/XML feeds.

**Comment by scroll** [comment]
@jtagcat Sorry, I'm just seeing this issue now. Let me see what I can do. It's a good idea to have RSS at least.

**Comment by scroll** [comment]
@jtagcat This is now done. You can get the feed from here https://marinpetrov.com/feed.xml Thank you for suggesting this.
